---
# tasks file for dns-server-install

- name: "Disable and stop bind service"
  ansible.builtin.service:
    name: bind9
    state: stopped
    enabled: false

- name: "Remove Bind9 packages"
  ansible.builtin.apt:
    update_cache: true
    state: absent
    autoclean: true
    autoremove: true
    purge: true
    pkg: 
    - bind9
    - bind9utils
    - bind9-doc
    - dnsutils

- name: Remove all direcory
  ansible.builtin.file:
    path: "{{ item }}" 
    state: absent
  with_items:
  - /etc/bind
  - /var/log/bind

  


