---
# tasks file for dns-server-install
- name: "Install Bind9 packages"
  ansible.builtin.apt:
    update_cache: true
    pkg: 
    - bind9
    - bind9utils
    - bind9-doc
    - dnsutils

- name: "Set hostname"
  ansible.builtin.hostname:
    name: "{{ bind_host }}.{{ bind_domain }}"

- name: Save old configuration files
  ansible.builtin.copy:
    src: /etc/bind/{{ item }}
    dest: /etc/bind/{{ item }}.BAK
    owner: root
    group: bind
    remote_src: yes
    backup: true
  with_items:
  - named.conf.local
  - named.conf.options

- name: Verify if db.{{ bind_domain }} exist
  local_action: stat path="db.{{ bind_domain }}"
  register: file   

- name: Save db.{{ bind_domain }} file
  ansible.builtin.copy:
    src: /etc/bind/db.{{ bind_domain }}
    dest: /etc/bind/db.{{ bind_domain }}.BAK
    owner: root
    group: bind
    remote_src: yes
    backup: true
  when: file.stat.exists

- name: Generate db.{{ bind_domain }} file
  template:
    src: ../templates/db.domain.j2
    dest: /etc/bind/db.{{ bind_domain }}
    owner: root
    group: bind
  
- name: Generate db files
  template:
    src: ../templates/{{ item }}.j2
    dest: /etc/bind/{{ item }}
    owner: root
    group: bind
  with_items:
  - named.conf.local
  - named.conf.options


- name: "Restart bind service"
  service:
    name: bind9
    state: restarted
    enabled: yes
